### ISSUE TITLE
[feat] Change all material imports to material3

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#105]
Throughout the wallet app, we are using both material and material 3. Change all material imports to material3 and remove the material dependency from the project build.gradle.kt file

#### References

![image](https://github.com/user-attachments/assets/bc652e03-8507-441a-b5e6-d4b5f595f40e)

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Hello I'm a frontend and a blockchain developer. I will love to work on this

**Comment by coxmars** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Hi @trbutler4, I'm a software developer with 2+ years of experience and I have worked with backend technologies such as Cairo, Java, C# and frontend with React, NextJS, JS/TS. Also, I'm a member of the Dojo Coding community here in CR and I have made contributions in Cairo VM Go, Cairo VM TS, Cairo Lints etc. Likewise, I’m a Cairo developer working on ByteBeasts, a fully on-chain RPG game built using the Dojo.

### How I plan on tackling this issue
- I’ll start by identifying all instances where material is imported throughout the app and replace them with material3 imports.
- After updating the imports, I will remove the material dependency from the build.gradle.kts file to clean up the project.
- Finally, I will test the app to ensure everything works correctly with material3 and address any potential issues that arise from the migration.

**Comment by Hoossayn** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I am a senior Android developer with 5+ years experience building scalable native android apps 

### How I plan on tackling this issue
- Remove the material dependency 
- fix errors that will come up due to this 
- replace material import with material 3 where necessary 

ETA: 2 hours

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Hi, I'm Collins a frontend and blockchain developer, and an active contributor on OnlyDust. You can check out my profile here: https://app.onlydust.com/u/0xdevcollins. This is my first time contributing to this repository, and I’m excited about the opportunity to contribute. Looking forward to collaborating!

### How I plan on tackling this issue
To update the wallet app to use Material 3 instead of Material, I will first review all the Kotlin files and replace any imports from the Material library with the corresponding Material 3 imports. I'll also adjust the usage of Material components to their Material 3 equivalents.

Next, I will open the build.gradle.kts file and remove any dependencies related to the Material library. I will ensure that the Material 3 dependency is included if it's not already present.

After making these changes, I will sync the Gradle files to apply the new dependencies. Finally, I will run the application to verify that all components function correctly with Material 3.

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I am a cairo dev. A new-comer here, willing and ready to contribute to contribute to solve the issue.

**Comment by PedroCo3lho** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I'm a software developer with experience in full-stack development, having worked with technologies such as Java, Flutter, Dart, Next.js, and C#. I'm also currently involved in developing Web3 projects, contributing to the Ethereum and Starknet ecosystems. My diverse technical background enables me to adapt to different frameworks and deliver effective solutions across various platforms.

### How I plan on tackling this issue
I would first locate all instances where Material is imported across the project and systematically replace them with Material 3 imports, ensuring that the components map correctly to their equivalents in Material 3. I would refer to the official documentation to confirm that each change retains the intended functionality. Finally, I would remove the Material dependency from the build.gradle.kts file to clean up unnecessary dependencies.

**Comment by trbutler4** [comment]
@coxmars Hey! Please let me know if you have any questions about the issue, You can ask here or send a message in the telegram group here: https://t.me/+8G3EBNnfyS1lNzYx

**Comment by coxmars** [comment]
> @coxmars Hey! Please let me know if you have any questions about the issue, You can ask here or send a message in the telegram group here: https://t.me/+8G3EBNnfyS1lNzYx

Thanks sir 🫡
