### ISSUE TITLE
[feat] Update hardcoded token price fetching to use currenly stored tokens

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#106]
Currently the balance fetching is just hardcoded to STRK and ETH . Update to get prices of all saved tokens. 

Search TODO(#106) to find where this is done. 

Requires #87

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Hello I'm a frontend and a blockchain developer. I will love to work on this issue

**Comment by Samuel1-ona** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

My background and how it can be leveraged
Hello  a blockchain developer. I will love to work on this issue

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
 My background in blockchain development and API integration equips me to efficiently handle this update while ensuring robust error handling and maintaining a smooth user experience.

### How I plan on tackling this issue
To solve the issue of updating balance fetching to include all saved tokens instead of just hardcoded STRK and ETH, I would start by locating the TODO comment (#106) in the codebase. Next, I would modify the balance fetching function to dynamically retrieve the prices of all saved tokens. This could involve integrating a price feed API or using a decentralized price oracle to ensure accurate and up-to-date token prices. I would also ensure that the implementation aligns with the requirements outlined in issue #87.

**Comment by jrmncos** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I'm a Software Enginer SR in web 2.0. Some tickets in this repo are not related exclusive with smart contracts, so my experience can work here. Also I have experience working on mobile. I will apply to various tickets in this repo, so sorry for the spam, I really like the project

### How I plan on tackling this issue
I will do the required in the description.

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I am a rust dev. A new-comer here, willing and ready to contribute to contribute to solve the issue.

**Comment by sajalbnl** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).
**My background and how it can be leveraged**
I am an Android developer with 2 years of experience in Kotlin, Jetpack Compose, and MVVM architecture. I’ve contributed to StarkNet Phone, building wallet and light client apps by integrating APIs and implementing UI/UX features. I'm excited to contribute my skills to this project . ETA - 1 Day
**How I plan on tackling this issue**
i have worked on this issue earlier also and taking reference from previous work will start my work
